DEVELOPERS 테이블에서 Front End 스킬을 가진 개발자의 정보를 조회
조건에 맞는 개발자의 ID, 이메일, 이름, 성을 조회하는 SQL 문을 작성
결과는 ID를 기준으로 오름차순 정렬

-- 1트(실패) : 오류 발생 'GROUP BY'
SELECT DEVELOP.ID, DEVELOP.EMAIL, DEVELOP.FIRST_NAME, DEVELOP.LAST_NAME
FROM SKILLCODES AS SKILL
JOIN DEVELOPERS AS DEVELOP
WHERE SKILL.CATEGORY = 'Front End' and
    DEVELOP.SKILL_CODE & SKILL.CODE != 0
GROUP BY SKILL.CATEGORY
ORDER BY DEVELOP.ID ASC

-- 2트(성공)
SELECT DISTINCT DEVELOP.ID, DEVELOP.EMAIL, DEVELOP.FIRST_NAME, DEVELOP.LAST_NAME
FROM SKILLCODES AS SKILL
JOIN DEVELOPERS AS DEVELOP
WHERE SKILL.CATEGORY = 'Front End' and
    DEVELOP.SKILL_CODE & SKILL.CODE != 0
ORDER BY DEVELOP.ID ASC