-- HR_DEPARTMENT, HR_EMPLOYEES, HR_GRADE 테이블을 이용해 사원별 성과금 정보를 조회
-- 사번, 성명, 평가 등급, 성과금을 조회
-- 평가등급의 컬럼명은 GRADE로, 성과금의 컬럼명은 BONUS로 해주세요.
-- 결과는 사번 기준으로 오름차순 정렬해주세요.

-- 1트(성공)
SELECT HREMPLOYEES.EMP_NO, HREMPLOYEES.EMP_NAME, 
    CASE 
        WHEN AVG(HRGRADE.SCORE) >= 96 THEN 'S'
        WHEN AVG(HRGRADE.SCORE) >= 90 THEN 'A'
        WHEN AVG(HRGRADE.SCORE) >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    (HREMPLOYEES.SAL * 
        CASE
            WHEN AVG(HRGRADE.SCORE) >= 96 THEN 0.2
            WHEN AVG(HRGRADE.SCORE) >= 90 THEN 0.15
            WHEN AVG(HRGRADE.SCORE) >= 80 THEN 0.1
            ELSE 0
        END) AS BONUS
FROM HR_EMPLOYEES AS HREMPLOYEES
JOIN HR_GRADE AS HRGRADE ON HREMPLOYEES.EMP_NO = HRGRADE.EMP_NO
GROUP BY HREMPLOYEES.EMP_NO
ORDER BY HREMPLOYEES.EMP_NO ASC